export const GET_EVENTLIST_DATA = "GET_EVENTLIST_DATA"
export const EVENTLIST_LOADING_STATUS = "EVENTLIST_LOADING_STATUS"
export const SET_EVENTSLIST_NUMBER_OF_PAGES = "SET_EVENTSLIST_NUMBER_OF_PAGES"
