export const SET_EVENTLIST_DATA = "SET_EVENTLIST_DATA"
export const EVENTLIST_LOADING_STATUS = "EVENTLIST_LOADING_STATUS"
export const SET_EVENTLIST_NUMBER_OF_PAGES = "SET_EVENTLIST_NUMBER_OF_PAGES"
export const SET_USER_LOCATION = "SET_USER_LOCATION"
